const metrics = [
  {
    title: "Population",
    value: "1.4B",
    description: "Total continental population",
    icon: "👥",
    color: "bg-indigo-500",
    trend: "up",
    change: "+1.2%",
  },
  {
    title: "GDP Growth",
    value: "3.8%",
    description: "Annual economic expansion",
    icon: "📈",
    color: "bg-emerald-500",
    trend: "up",
    change: "+0.3%",
  },
  {
    title: "Urbanization",
    value: "43%",
    description: "Living in cities",
    icon: "🏙️",
    color: "bg-amber-500",
    trend: "up",
    change: "+0.9%",
  },
  {
    title: "Mobile Users",
    value: "84%",
    description: "Mobile penetration rate",
    icon: "📱",
    color: "bg-blue-500",
    trend: "up",
    change: "+1.8%",
  },
  {
    title: "Youth Unemploy.",
    value: "12.8%",
    description: "Ages 15-24",
    icon: "🧑‍🎓",
    color: "bg-rose-500",
    trend: "down",
    change: "-0.5%",
  },
  {
    title: "Renewables",
    value: "22%",
    description: "Energy production",
    icon: "☀️",
    color: "bg-green-500",
    trend: "up",
    change: "+0.7%",
  },
];

export default metrics;
