 const metrics = [
    {
      title: "Population",
      value: "1.4B",
      change: "+2.5%",
      trend: "up",
      description: "Total continental population",
      icon: "👥",
      color: "bg-indigo-500",
    },
    {
      title: "GDP Growth",
      value: "3.8%",
      change: "+0.4%",
      trend: "up",
      description: "Annual economic expansion",
      icon: "📈",
      color: "bg-emerald-500",
    },
    {
      title: "Urbanization",
      value: "43%",
      change: "+1.2%",
      trend: "up",
      description: "Living in cities",
      icon: "🏙️",
      color: "bg-amber-500",
    },
    {
      title: "Mobile Users",
      value: "84%",
      change: "+6%",
      trend: "up",
      description: "Mobile penetration rate",
      icon: "📱",
      color: "bg-blue-500",
    },
    {
      title: "Youth Unemploy.",
      value: "12.8%",
      change: "-0.7%",
      trend: "down",
      description: "Ages 15-24",
      icon: "🧑‍🎓",
      color: "bg-rose-500",
    },
    {
      title: "Renewables",
      value: "22%",
      change: "+3.1%",
      trend: "up",
      description: "Energy production",
      icon: "☀️",
      color: "bg-green-500",
    },
  ];
  export default metrics;